title: Nguyễn Trần Thức
subtitle: Personal site
description: >- # this means to ignore newlines until "baseurl:"
  Personal site of Raquel Peces (a.k.a. raquelFishes)

url: "https://tranthuc99.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Về Tôi
      url: /about
    - text: Blog
      url: /blog
    - text: Hình Ảnh
      url: /gallery
    #- text: Cửa Hàng
    #  url : /shop
    - text: Liên Hệ
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: profile.webp
author: Nguyễn Trần Thức
author_name: Nguyễn Trần
author_lastname: Thức
author_bio: Hi, my name is Thuc. I am a Developer and a Photographer :D
author_email: "tranthuc1199@gmail.com"
author_location: Thái Nguyên, Việt Nam
author_website_url: "http://nguyentranthuc.tk"
typewrite-text: I am a Developer and a Photographer =))
typewrite-title:
  - Welcome to personal site of me !!
  - I am a Developer and a Photographer =)) 


author_work_experiences:
            - company_name: ICOMM Media & Tech, Jsc
              company_logo: logo-icomm.webp
              company_url: https://icomm.vn
              designation: R & D trainee
              description: Working on NLP project
              visibility: true
            #- company_name: Ilion Animation Studios
             # company_logo: ilion.webp
              #company_url: https://ilion.com
              #designation: Technical Director CFX, FX and Crowds
              #description: Worked on several departments developing tools to improve artists pipeline
              #visibility: true

author_education_details:
              - college_logo: logoBK.webp
                college_name: HUST
                college_url: https://www.hust.edu.vn/
                college_degree: Bachelor In Management Information System
                #description: Computer Graphics, Games and Virtual Reality
                visibility: true
              #- college_logo: ucm.webp
               # college_name: UCM
                #college_url: https://ucm.es
                #college_degree: Computer Engineer
                #description: Computer Science Degree
                #visibility: true

                
# author_project_details:
#               - project_thumbnail: gamershub.png
#                 project_title: Gamers Hub
#                 project_description: A Platform built for Gamers and Game Devs
#                 project_url: https://gamershub.in
#                 visibility: true
#               - project_thumbnail: hack4r.PNG
#                 project_title: Hack4r
#                 project_description: A Platform built for Hackers and Penetration Testers
#                 project_url: https://hack4r.com
#                 visibility: true

# social links
twitter_username: null
github_username:  tranthuc99
facebook_username: tranthuc140820
linkedin_username: thuc-nguyen-4941181ab
behance_username: null
instagram_username: null
medium_username: null
telegram_username: null
dribbble_username: null
flickr_username: null
spotify_username: null

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: Thức

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: xwkrklev

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-166953347-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
